export const ACTIONS = {
    INITIALIZE: 'INITIALIZE',
    GET_USERS: 'GET_USERS',
    GET_PROFILE: 'GET_PROFILE',
    GET_USER: 'GET_USER',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    PATCH_USER: 'PATCH_USER',
    DELETE_USER: 'DELETE_USER',
    ADMIN_CREATE_USER: 'ADMIN_CREATE_USER',
    GET_WHATSAPP_ALERTS: 'GET_WHATSAPP_ALERTS',
    SEND_WHATSAPP_ALERT: 'SEND_WHATSAPP_ALERT',
  };
  